/** Bidirectional irregular word pairs: [singular, plural] */
const pairs: [string, string][] = [
  ["I", "we"],
  ["me", "us"],
  ["he", "they"],
  ["she", "they"],
  ["them", "them"],
  ["myself", "ourselves"],
  ["yourself", "yourselves"],
  ["itself", "themselves"],
  ["herself", "themselves"],
  ["himself", "themselves"],
  ["themself", "themselves"],
  ["is", "are"],
  ["was", "were"],
  ["has", "have"],
  ["this", "these"],
  ["that", "those"],
  ["my", "our"],
  ["its", "their"],
  ["his", "their"],
  ["her", "their"],
  ["echo", "echoes"],
  ["dingo", "dingoes"],
  ["volcano", "volcanoes"],
  ["tornado", "tornadoes"],
  ["torpedo", "torpedoes"],
  ["domino", "dominoes"],
  ["veto", "vetoes"],
  ["mosquito", "mosquitoes"],
  ["animus", "animi"],
  ["apparatus", "apparatus"],
  ["impetus", "impetus"],
  ["incubus", "incubi"],
  ["map", "maps"],
  ["mavis", "mavises"],
  ["niche", "niches"],
  ["oasis", "oases"],
  ["opus", "opera"],
  ["ox", "oxen"],
  ["penis", "penises"],
  ["person", "people"],
  ["sex", "sexes"],
  ["soliloquy", "soliloquies"],
  ["testis", "testes"],
  ["trilby", "trilbies"],
  ["turf", "turfs"],
  ["potato", "potatoes"],
  ["hero", "heroes"],
  ["tooth", "teeth"],
  ["goose", "geese"],
  ["foot", "feet"],
  ["foe", "foes"],
  ["man", "men"],
  ["woman", "women"],
  ["child", "children"],
  ["move", "moves"],
  ["zombie", "zombies"],
  ["genus", "genera"],
  ["quiz", "quizzes"],
  ["human", "humans"],
  ["glove", "gloves"],
  ["wave", "waves"],
  ["slave", "slaves"],
  ["native", "natives"],
  ["cave", "caves"],
  ["valve", "valves"],
  ["nerve", "nerves"],
  ["dove", "doves"],
  ["above", "aboves"],
  ["stove", "stoves"],
  ["grove", "groves"],
  ["drive", "drives"],
  ["hive", "hives"],
  ["give", "gives"],
  ["leaf", "leaves"],
  ["life", "lives"],
  ["olive", "olives"],
  ["relative", "relatives"],
  ["archive", "archives"],
  ["perspective", "perspectives"],
  ["objective", "objectives"],
  ["initiative", "initiatives"],
  ["executive", "executives"],
  ["detective", "detectives"],
  ["adjective", "adjectives"],
  ["alternative", "alternatives"],
  ["representative", "representatives"],
  ["narrative", "narratives"],
  ["locomotive", "locomotives"],
  ["motive", "motives"],
  ["cookie", "cookies"],
  ["rookie", "rookies"],
  ["movie", "movies"],
  ["collie", "collies"],
  ["calorie", "calories"],
  ["brownie", "brownies"],
  ["genie", "genies"],
  ["eerie", "eeries"],
  ["birdie", "birdies"],
  ["pixie", "pixies"],
  ["hippie", "hippies"],
  ["zombie", "zombies"],
  ["smoothie", "smoothies"],
  ["prairie", "prairies"],
  ["goalie", "goalies"],
  ["caddie", "caddies"],
  ["veggie", "veggies"],
  ["selfie", "selfies"],
  ["techie", "techies"],
  ["newbie", "newbies"],
  ["foodie", "foodies"],
];

/** Map: singular (lowercase) → plural (lowercase) */
export const singularToPlural = new Map<string, string>();

/** Map: plural (lowercase) → singular (lowercase) */
export const pluralToSingular = new Map<string, string>();

for (const [s, p] of pairs) {
  singularToPlural.set(s.toLowerCase(), p.toLowerCase());
  pluralToSingular.set(p.toLowerCase(), s.toLowerCase());
}

/** Add a custom irregular pair */
export function addIrregular(singular: string, plural: string): void {
  singularToPlural.set(singular.toLowerCase(), plural.toLowerCase());
  pluralToSingular.set(plural.toLowerCase(), singular.toLowerCase());
}
