/** Set of uncountable words (lowercase). These words have the same singular and plural form. */
export const uncountables = new Set<string>([
  "adulthood",
  "advice",
  "agenda",
  "aid",
  "aircraft",
  "alcohol",
  "ammo",
  "analytics",
  "anime",
  "athletics",
  "bison",
  "blood",
  "bream",
  "buffalo",
  "butter",
  "carp",
  "cash",
  "chassis",
  "chess",
  "clothing",
  "cod",
  "commerce",
  "cooperation",
  "corps",
  "debris",
  "deceased",
  "deer",
  "diabetes",
  "digestion",
  "elk",
  "electricity",
  "emoji",
  "equipment",
  "evidence",
  "evolution",
  "faith",
  "feedback",
  "firmware",
  "fish",
  "flora",
  "flounder",
  "fun",
  "furniture",
  "gallows",
  "garbage",
  "gold",
  "golf",
  "graffiti",
  "grass",
  "grouse",
  "hardware",
  "headquarters",
  "health",
  "herpes",
  "hertz",
  "highs",
  "homework",
  "honesty",
  "ice",
  "information",
  "jeans",
  "justice",
  "kudos",
  "labour",
  "labor",
  "legislation",
  "leisure",
  "linguistics",
  "livestock",
  "lows",
  "luggage",
  "machinery",
  "mackerel",
  "mail",
  "malarkey",
  "manga",
  "mathematics",
  "media",
  "mews",
  "metadata",
  "money",
  "moose",
  "music",
  "mud",
  "manga",
  "news",
  "nutrition",
  "offspring",
  "plankton",
  "pliers",
  "police",
  "pollution",
  "premises",
  "rain",
  "racism",
  "research",
  "rice",
  "salmon",
  "scissors",
  "series",
  "sewage",
  "shambles",
  "sheep",
  "shrimp",
  "software",
  "spam",
  "species",
  "staff",
  "swine",
  "tennis",
  "thanks",
  "traffic",
  "transportation",
  "trousers",
  "trout",
  "tuna",
  "vermicelli",
  "weather",
  "wheat",
  "whitebait",
  "wholesale",
  "wildlife",
  "willpower",
  "you",
]);

/** Regex patterns for uncountable words */
export const uncountablePatterns: RegExp[] = [];

/** Add a custom uncountable word or pattern */
export function addUncountable(word: string | RegExp): void {
  if (word instanceof RegExp) {
    uncountablePatterns.push(word);
  } else {
    uncountables.add(word.toLowerCase());
  }
}

/** Check if a word is uncountable */
export function isUncountable(word: string): boolean {
  const lower = word.toLowerCase();
  if (uncountables.has(lower)) return true;
  for (const pattern of uncountablePatterns) {
    if (pattern.test(word)) return true;
  }
  return false;
}
